[rewrite_local]
^https?:\/\/.*\.pangle\.com\/.* url reject
^https?:\/\/.*\.snssdk\.com\/.*ad.* url reject
^https?:\/\/.*\.snssdk\.com\/.*reward.* url reject
^https?:\/\/[\w-]*\.douyin\.com\/aweme\/v1\/web\/play\/? url reject-200
^https?:\/\/aweme\.amemv\.com\/aweme\/v1\/web\/play\/ url reject-200

[mitm]
hostname = *.snssdk.com,*.pangle.com,*.douyin.com,aweme.amemv.com
